version: '3'
 
services:
  gameclient:
    image: gameclient
    hostname: gameclient
    ports:
     - 5000:5000
     - 5006:5006
    restart: always
    networks:
      - game-service-network
    volumes:
      - ./GameClient:/app

  gameclient2:
    image: gameclient
    hostname: gameclient2
    ports:
     - 5010:5000
    restart: always
    networks:
      - game-service-network
    volumes:
      - ./GameClient:/app

  gamelobby:
    image: gamelobby
    hostname: gamelobby
    ports:
     - 5005:5005
    restart: always
    networks:
      - game-service-network
      - database-network
    volumes:
      - ./GameLobby:/app

  gameservice:
    image: gameservice
    hostname: gameservice
    ports:
     - 7549:7549
    restart: always
    depends_on:
      - database
    networks:
      - game-service-network
      - database-network
    volumes:
      - ./GameService:/app
      
  database:
    image: mysql:5.5
    hostname: database
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_DATABASE: Users
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./Database:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - database-network

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  game-service-network:
    driver: overlay
  database-network:
    driver: overlay